<?php /* Smarty version 2.6.25, created on 2017-04-15 20:09:48
         compiled from tpl_top:23 */

$this->_cache_serials['/home/valeksa/public_html/tmp/templates_c/%%25^25E^25E0F81D%%tpl_top%3A23.inc'] = 'f0e4f1b989c9448a4b77f320a3396694';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_include', 'tpl_top:23', 1, false),array('function', 'cms_module', 'tpl_top:23', 3, false),array('function', 'content', 'tpl_top:23', 5, false),)), $this); ?>
<?php
function _smarty_tplfunc_f0e4f1b989c9448a4b77f320a3396694_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f0e4f1b989c9448a4b77f320a3396694','0');echo cms_tmp_cms_include_userplugin_function(array('tpl' => 'header'), $_smarty);
}


function _smarty_tplfunc_f0e4f1b989c9448a4b77f320a3396694_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f0e4f1b989c9448a4b77f320a3396694','1');echo smarty_cms_function_cms_module(array('module' => 'Titulinis','kategorija' => 'foto','kalba' => $_smarty->_tpl_vars['kalba']), $_smarty);
}


function _smarty_tplfunc_f0e4f1b989c9448a4b77f320a3396694_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f0e4f1b989c9448a4b77f320a3396694','2');echo smarty_cms_function_content(array('label' => 'Nuoroda 1','block_group' => 'Blokeliai','block' => 'link1','collapse' => 'false','assign' => 'link1','oneline' => true), $_smarty);
}


function _smarty_tplfunc_f0e4f1b989c9448a4b77f320a3396694_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f0e4f1b989c9448a4b77f320a3396694','3');echo smarty_cms_function_content(array('label' => 'Blokelis 1','block_group' => 'Blokeliai','block' => 'block1','collapse' => 'false','assign' => 'block1'), $_smarty);
}


function _smarty_tplfunc_f0e4f1b989c9448a4b77f320a3396694_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f0e4f1b989c9448a4b77f320a3396694','4');echo smarty_cms_function_content(array('label' => 'Nuoroda 2','block_group' => 'Blokeliai','block' => 'link2','collapse' => 'false','assign' => 'link2','oneline' => true), $_smarty);
}


function _smarty_tplfunc_f0e4f1b989c9448a4b77f320a3396694_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f0e4f1b989c9448a4b77f320a3396694','5');echo smarty_cms_function_content(array('label' => 'Blokelis 2','block_group' => 'Blokeliai','block' => 'block2','collapse' => 'false','assign' => 'block2'), $_smarty);
}


function _smarty_tplfunc_f0e4f1b989c9448a4b77f320a3396694_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f0e4f1b989c9448a4b77f320a3396694','6');echo smarty_cms_function_content(array('label' => 'Nuoroda 3','block_group' => 'Blokeliai','block' => 'link3','collapse' => 'false','assign' => 'link3','oneline' => true), $_smarty);
}


function _smarty_tplfunc_f0e4f1b989c9448a4b77f320a3396694_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f0e4f1b989c9448a4b77f320a3396694','7');echo smarty_cms_function_content(array('label' => 'Blokelis 3','block_group' => 'Blokeliai','block' => 'block3','collapse' => 'false','assign' => 'block3'), $_smarty);
}


function _smarty_tplfunc_f0e4f1b989c9448a4b77f320a3396694_8(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f0e4f1b989c9448a4b77f320a3396694','8');echo smarty_cms_function_content(array('label' => 'Nuoroda 4','block_group' => 'Blokeliai','block' => 'link4','collapse' => 'false','assign' => 'link4','oneline' => true), $_smarty);
}


function _smarty_tplfunc_f0e4f1b989c9448a4b77f320a3396694_9(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f0e4f1b989c9448a4b77f320a3396694','9');echo smarty_cms_function_content(array('label' => 'Blokelis 4','block_group' => 'Blokeliai','block' => 'block4','collapse' => 'false','assign' => 'block4'), $_smarty);
}


function _smarty_tplfunc_f0e4f1b989c9448a4b77f320a3396694_10(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f0e4f1b989c9448a4b77f320a3396694','10');echo smarty_cms_function_content(array('label' => 'Tekstas po blokeliais','block_group' => 'Turinys','block' => 'pofoto','collapse' => 'false','assign' => 'pofoto'), $_smarty);
}


function _smarty_tplfunc_f0e4f1b989c9448a4b77f320a3396694_11(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('f0e4f1b989c9448a4b77f320a3396694','11');echo cms_tmp_cms_include_userplugin_function(array('tpl' => 'footer'), $_smarty);
}



?>
