<?php /* Smarty version 2.6.25, created on 2017-04-15 19:56:13
         compiled from tpl_top:38 */

$this->_cache_serials['/home/valeksa/public_html/tmp/templates_c/%%AB^AB2^AB2910D4%%tpl_top%3A38.inc'] = '7ef2347c023cda6de7ad076774765a6d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_include', 'tpl_top:38', 1, false),array('function', 'menu', 'tpl_top:38', 14, false),array('function', 'title', 'tpl_top:38', 17, false),array('function', 'content', 'tpl_top:38', 18, false),array('modifier', 'check_headimg', 'tpl_top:38', 4, false),)), $this); ?>
<?php
function _smarty_tplfunc_7ef2347c023cda6de7ad076774765a6d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ef2347c023cda6de7ad076774765a6d','0');echo cms_tmp_cms_include_userplugin_function(array('tpl' => 'header'), $_smarty);
}


function _smarty_tplfunc_7ef2347c023cda6de7ad076774765a6d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ef2347c023cda6de7ad076774765a6d','1');echo smarty_cms_function_menu(array('template' => 'leftmenu','collapse' => '1','start_level' => 3,'number_of_levels' => 3), $_smarty);
}


function _smarty_tplfunc_7ef2347c023cda6de7ad076774765a6d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ef2347c023cda6de7ad076774765a6d','2');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_7ef2347c023cda6de7ad076774765a6d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ef2347c023cda6de7ad076774765a6d','3');echo smarty_cms_function_content(array(), $_smarty);
}


function _smarty_tplfunc_7ef2347c023cda6de7ad076774765a6d_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7ef2347c023cda6de7ad076774765a6d','4');echo cms_tmp_cms_include_userplugin_function(array('tpl' => 'footer'), $_smarty);
}



?>
