<?php /* Smarty version 2.6.25, created on 2017-04-15 21:36:37
         compiled from tpl_top:35 */

$this->_cache_serials['/home/valeksa/public_html/tmp/templates_c/%%D5^D59^D5986C69%%tpl_top%3A35.inc'] = '0bfa185938a98e34562c85f6c712538d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_include', 'tpl_top:35', 1, false),array('function', 'menu', 'tpl_top:35', 14, false),array('function', 'title', 'tpl_top:35', 17, false),array('function', 'content', 'tpl_top:35', 18, false),array('modifier', 'check_headimg', 'tpl_top:35', 4, false),)), $this); ?>
<?php
function _smarty_tplfunc_0bfa185938a98e34562c85f6c712538d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0bfa185938a98e34562c85f6c712538d','0');echo cms_tmp_cms_include_userplugin_function(array('tpl' => 'header'), $_smarty);
}


function _smarty_tplfunc_0bfa185938a98e34562c85f6c712538d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0bfa185938a98e34562c85f6c712538d','1');echo smarty_cms_function_menu(array('template' => 'leftmenu','collapse' => '1','start_level' => 3,'number_of_levels' => 3), $_smarty);
}


function _smarty_tplfunc_0bfa185938a98e34562c85f6c712538d_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0bfa185938a98e34562c85f6c712538d','2');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_0bfa185938a98e34562c85f6c712538d_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0bfa185938a98e34562c85f6c712538d','3');echo smarty_cms_function_content(array('block' => 'turinys','label' => 'Turinys'), $_smarty);
}


function _smarty_tplfunc_0bfa185938a98e34562c85f6c712538d_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0bfa185938a98e34562c85f6c712538d','4');echo cms_tmp_cms_include_userplugin_function(array('tpl' => 'footer'), $_smarty);
}



?>
