<?php /* Smarty version 2.6.25, created on 2021-07-26 14:29:29
         compiled from content:turinys */

$this->_cache_serials['/home/valeksa/public_html/tmp/templates_c/1660^%%29^292^2923CF6D%%content%3Aturinys.inc'] = 'a442ac85977fdb038ad2fe41125588de';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'TxForm', 'content:turinys', 19, false),)), $this); ?>
<?php
function _smarty_tplfunc_a442ac85977fdb038ad2fe41125588de_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('a442ac85977fdb038ad2fe41125588de','0');echo $_smarty->_plugins['function']['TxForm'][0][0]->function_plugin(array('form' => '1'), $_smarty);
}



?>
