<?php /* Smarty version 2.6.25, created on 2017-04-16 03:40:13
         compiled from content:content_en */

$this->_cache_serials['/home/valeksa/public_html/tmp/templates_c/1688^%%70^707^707A8977%%content%3Acontent_en.inc'] = '43df61336c876b0766e0aa152fbb1e1b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_module', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_43df61336c876b0766e0aa152fbb1e1b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('43df61336c876b0766e0aa152fbb1e1b','0');echo smarty_cms_function_cms_module(array('module' => 'news','category' => 'parduodamas_turtas_en','pagelimit' => 10), $_smarty);
}



?>
