<?php /* Smarty version 2.6.25, created on 2018-03-12 13:18:32
         compiled from module_file_tpl:AdvancedContent%3Bheader.tpl */

$this->_cache_serials['/home/valeksa/public_html/tmp/templates_c/AdvancedContent^%%06^063^06364507%%module_file_tpl%3AAdvancedContent%3Bheader.tpl.inc'] = '0f704c29a713ef8f8cc59ead2b367453';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'root_url', 'module_file_tpl:AdvancedContent;header.tpl', 14, false),array('modifier', 'count', 'module_file_tpl:AdvancedContent;header.tpl', 15, false),)), $this); ?>
<?php
function _smarty_tplfunc_0f704c29a713ef8f8cc59ead2b367453_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0f704c29a713ef8f8cc59ead2b367453','0');echo smarty_function_root_url(array(), $_smarty);
}


function _smarty_tplfunc_0f704c29a713ef8f8cc59ead2b367453_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0f704c29a713ef8f8cc59ead2b367453','1');echo smarty_function_root_url(array(), $_smarty);
}


function _smarty_tplfunc_0f704c29a713ef8f8cc59ead2b367453_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('0f704c29a713ef8f8cc59ead2b367453','2');echo smarty_function_root_url(array(), $_smarty);
}



?>
