<?php /* Smarty version 2.6.25, created on 2017-04-15 19:56:13
         compiled from module_db_tpl:Album%3Bdefault */

$this->_cache_serials['/home/valeksa/public_html/tmp/templates_c/Album^%%B9^B9B^B9B62FDB%%module_db_tpl%3AAlbum%3Bdefault.inc'] = '4990d3a90ba0069d2e9c685132cbce8d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'root_url', 'module_db_tpl:Album;default', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_4990d3a90ba0069d2e9c685132cbce8d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4990d3a90ba0069d2e9c685132cbce8d','0');echo smarty_function_root_url(array(), $_smarty);
}


function _smarty_tplfunc_4990d3a90ba0069d2e9c685132cbce8d_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4990d3a90ba0069d2e9c685132cbce8d','1');echo smarty_function_root_url(array(), $_smarty);
}



?>
