<?php /* Smarty version 2.6.25, created on 2021-07-26 14:24:52
         compiled from module_file_tpl:Album%3Bcategorylist.tpl */

$this->_cache_serials['/home/valeksa/public_html/tmp/templates_c/Album^%%FC^FC3^FC313757%%module_file_tpl%3AAlbum%3Bcategorylist.tpl.inc'] = 'be4611c7102ac3cbcdfbf76b59697fd3';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cycle', 'module_file_tpl:Album;categorylist.tpl', 15, false),)), $this); ?>
<?php
function _smarty_tplfunc_be4611c7102ac3cbcdfbf76b59697fd3_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('be4611c7102ac3cbcdfbf76b59697fd3','0');echo smarty_function_cycle(array('values' => "row1,row2",'assign' => 'rowclass'), $_smarty);
}



?>
