<?php /* Smarty version 2.6.25, created on 2017-04-15 20:00:09
         compiled from module_file_tpl:Album%3Bbrowsepictures.tpl */

$this->_cache_serials['/home/valeksa/public_html/tmp/templates_c/Album^%%7C^7CC^7CCB7AC7%%module_file_tpl%3AAlbum%3Bbrowsepictures.tpl.inc'] = '8cdbb95249eaffe305a2472bfd0efe9f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cycle', 'module_file_tpl:Album;browsepictures.tpl', 16, false),)), $this); ?>
<?php
function _smarty_tplfunc_8cdbb95249eaffe305a2472bfd0efe9f_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8cdbb95249eaffe305a2472bfd0efe9f','0');echo smarty_function_cycle(array('values' => '1,2','advance' => false), $_smarty);
}


function _smarty_tplfunc_8cdbb95249eaffe305a2472bfd0efe9f_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8cdbb95249eaffe305a2472bfd0efe9f','1');echo smarty_function_cycle(array('values' => '1,2'), $_smarty);
}


function _smarty_tplfunc_8cdbb95249eaffe305a2472bfd0efe9f_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8cdbb95249eaffe305a2472bfd0efe9f','2');echo smarty_function_cycle(array('values' => '1,2','advance' => false), $_smarty);
}


function _smarty_tplfunc_8cdbb95249eaffe305a2472bfd0efe9f_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8cdbb95249eaffe305a2472bfd0efe9f','3');echo smarty_function_cycle(array('values' => '1,2','advance' => false), $_smarty);
}


function _smarty_tplfunc_8cdbb95249eaffe305a2472bfd0efe9f_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('8cdbb95249eaffe305a2472bfd0efe9f','4');echo smarty_function_cycle(array('values' => '1,2'), $_smarty);
}



?>
