<?php /* Smarty version 2.6.25, created on 2017-04-15 20:09:49
         compiled from module_file_tpl:Titulinis%3Bw_foto.tpl */

$this->_cache_serials['/home/valeksa/public_html/tmp/templates_c/Titulinis^%%A7^A7C^A7C340C9%%module_file_tpl%3ATitulinis%3Bw_foto.tpl.inc'] = '7e5f6e5b5cc87dbfb6fb46f0a373c072';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'root_url', 'module_file_tpl:Titulinis;w_foto.tpl', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_7e5f6e5b5cc87dbfb6fb46f0a373c072_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7e5f6e5b5cc87dbfb6fb46f0a373c072','0');echo smarty_function_root_url(array(), $_smarty);
}


function _smarty_tplfunc_7e5f6e5b5cc87dbfb6fb46f0a373c072_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('7e5f6e5b5cc87dbfb6fb46f0a373c072','1');echo smarty_function_root_url(array(), $_smarty);
}



?>
