<?php /* Smarty version 2.6.25, created on 2017-04-16 00:44:21
         compiled from module_file_tpl:TxForm%3Buzklausa.tpl */

$this->_cache_serials['/home/valeksa/public_html/tmp/templates_c/TxForm^%%FC^FCE^FCEAD581%%module_file_tpl%3ATxForm%3Buzklausa.tpl.inc'] = '88b6cae96ba4fb657d639f555ce05414';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'field', 'module_file_tpl:TxForm;uzklausa.tpl', 11, false),)), $this); ?>
<?php
function _smarty_tplfunc_88b6cae96ba4fb657d639f555ce05414_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('88b6cae96ba4fb657d639f555ce05414','0');echo smarty_function_field(array('type' => 'text','name' => 'vardas','label' => '0','prefix' => $_smarty->_tpl_vars['prefix'],'defval' => $_smarty->_tpl_vars['vardas']), $_smarty);
}


function _smarty_tplfunc_88b6cae96ba4fb657d639f555ce05414_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('88b6cae96ba4fb657d639f555ce05414','1');echo smarty_function_field(array('type' => 'text','name' => 'elpastas','prefix' => $_smarty->_tpl_vars['prefix'],'label' => '0','required' => 1,'defval' => $_smarty->_tpl_vars['elpastas']), $_smarty);
}


function _smarty_tplfunc_88b6cae96ba4fb657d639f555ce05414_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('88b6cae96ba4fb657d639f555ce05414','2');echo smarty_function_field(array('type' => 'textarea','name' => 'zinute','prefix' => $_smarty->_tpl_vars['prefix'],'label' => '0','defval' => $_smarty->_tpl_vars['zinute'],'rows' => '30','cols' => '5'), $_smarty);
}



?>
